### ISSUE TITLE
front body twinsor file...

### ISSUE THREAD

**Issue by 3Dgraf64** [IRTrail/Voron-Stuff#2]
Hi!  I'm getting into this mod and printed all the files.  But the bearing's place is a 3.5 mm wide rectangular hole for both stl and 3mf files.  Printed the "front body twinsor" from the step file who have the correct 6mm ball holes.  The issue for this on is for the bottom switch:  The switch/ball does'nt go far enough in the filament path.  So the switch won't operate.  Using Freecad and trying to solve this.
Top switch is working fine.  Thanks for this mod.
Francis

**Comment by IRTrail** [comment]
I directly downloaded the STL from my repo and interrogated it in F360, MS 3D viewer, and Solidworks. None have the issue you describe and the holes for the 5.5mm ball are shaped correctly. I am not familiar with FreeCad so I can't help you there.

![image](https://github.com/IRTrail/Voron-Stuff/assets/53546870/f333ad94-ded7-45a2-a863-1a3e7518072f)

The position of the switch and ball cavity compared to the center of the filament path is the same for both switches. This was a sticking point during testing. During testing it was found these switches are extremely sensitive to placement and it was found there is only about 0.2mm "wiggle room" to get them actuating reliably. The switch itself has a travel range of 0.5mm with 0.25mm overtravel. So, the target sweet spot is less than a printed layer. If there are any blobs at the sharp corners of the filament path to ball chamber interface or z seam artifacts near the nose of the cavity, I could see that causing some issues. Unfortunately, this setup is finicky with print quality, and it has to be spot on. That being said, there are many in service already that aren't duplicating your issue. I'll print another directly from the downloaded STL and check it again.

**Comment by 3Dgraf64** [comment]
![Sans titre1](https://github.com/IRTrail/Voron-Stuff/assets/92392776/d0924749-e3cd-4629-806e-802b87937ce7)
![20240117_092222](https://github.com/IRTrail/Voron-Stuff/assets/92392776/4be0167c-de9f-46a5-8718-9d703c352a91)
![20240117_092325](https://github.com/IRTrail/Voron-Stuff/assets/92392776/3c1be99b-548f-429e-8c3d-1b7d5a480305)
Here are picts of my stl print (Voron specs of course).  Check the ball housing.

**Comment by IRTrail** [comment]
You're using an old version. I originally started with 6x3 magnets instead of the bearings. Please use the current models in the repo. That version is depreciated and unsupported.

**Comment by 3Dgraf64** [comment]
Thanks a lot!
