### ISSUE TITLE
Single sensor body is missing the pocket for the ball bearing

### ISSUE THREAD

**Issue by StealthViper27** [IRTrail/Voron-Stuff#3]
![image](https://github.com/IRTrail/Voron-Stuff/assets/72460976/557d822a-ec4f-47d4-bd1c-a2d7a986c1e5)
The single sensor body for the G2E Filametrix mod is missing the pocket for the ball bearing for the filament to trigger the sensor.

**Comment by IRTrail** [comment]
My apologies and thank you for reporting that.
Should be fixed now. Updated STL and 3MF Front Body Single files.
