### ISSUE TITLE
G2E Rapido 2 UHF front part seems to be un-modded

### ISSUE THREAD

**Issue by dflemstr** [IRTrail/Voron-Stuff#4]
The file at `G2E Filametrix Mod/Other Printheads/Rapido 2 UHF/STL/SB Rapido 2 UHF.STL` seems to be unmodified from the original non-filametrix version of the file.  I wonder if this is as simple as forgetting to export the modded version?

**Comment by IRTrail** [comment]
Have a look here and see if they look better now:

https://github.com/IRTrail/G2E-Filametrix/tree/main/Other%20Printheads/Rapido%202%20UHF

I recently split the folder out of the Voron-Stuff repo to it's own repo. You were right though, they were not updated files. Thanks for letting me know!
